### ISSUE TITLE
 Timed out waiting for account MetApi

### ISSUE THREAD

**Issue by cslimani** [agiliumtrade-ai/metaapi-java-sdk#9]
Hello,

I am trying to run the file StreamQuotesExample but I get the following exception most of the time : 
`java.util.concurrent.ExecutionException: cloud.metaapi.sdk.clients.TimeoutException: Timed out waiting for account MetApi to synchronize to MetaTrader account 6453ad7f-..., synchronization id null`

Sometimes it work but most of the time it ends up with a timeout.
It works very well with Python and Node.JS

**Comment by oleksiilogvin** [comment]
The same issue during the synchronization: 
`metaApiConnection.waitSynchronized().join();`

**Comment by RomanKisilenko** [comment]
The Java SDK was updated long time ago and lacks important bugfixes and updates, and in order to access our service using Java SDK you need to request an explicit permission to do so via online chat. We plan to update the java SDK sometime in future. Meanwhile we recommend you to use javascript or python SDK instead.
